using Content.Client.ADT.Discord;
using Content.Client.Corvax.Sponsors;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Shared.ADT.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly SponsorsManager _sponsorsManager = default!;
        [Dependency] private readonly DiscordIdManager _discordIdManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        private float _updateTimer;
        private bool _panelUpdate = false;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            // ADT-Tweak-Start
            HideInterface.OnPressed += _ =>
            {
                SwitchState(LobbyGuiState.ScreenSaver);
            };
            ShowInterface.OnPressed += _ =>
            {
                SwitchState(LobbyGuiState.Default);
            };

            if (_cfg.GetCVar(ADTCCVars.ExtraLobbyPanelEnabled))
            {
                LobbyPanelLeftTop.Visible = true;
                _panelUpdate = true;
                UpdateButtons();
            }
            else
            {
                _panelUpdate = false;
                LobbyPanelLeftTop.Visible = false;
            }
            // ADT-Tweak-End

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;


            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;

            }
        }



        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup,
            ScreenSaver, // ADT-Tweak
        }
    }
}
